apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kubernetes
  - trusted-private-egress.yaml

patches:
  - target:
      kind: ConfigMap
      name: site-checker-config
    patch: |-
      - op: replace
        path: /data/ALLOW_PRIVATE_NETWORKS
        value: "true"
