apiVersion: v1
kind: Service
metadata:
  name: site-checker-api
  namespace: site-checker
  labels:
    app.kubernetes.io/name: site-checker
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: site-checker
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8080
      targetPort: http
